#!/bin/sh /etc/rc.common
USE_PROCD=1
START=99
STOP=10
start_service(){
  procd_open_instance
  procd_set_param command /usr/bin/kee-route-manager serve --config /etc/kee-route-manager/config.yaml
  procd_set_param respawn 3600 5 5
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_set_param limits nofile="4096 4096"
  procd_close_instance
}
service_triggers(){ procd_add_reload_trigger kee-route-manager; }
reload_service(){ stop; start; }
