#!/bin/sh /etc/rc.common
# procd/rc.common reads these variables externally.
# shellcheck disable=SC2034
USE_PROCD=1
# shellcheck disable=SC2034
START=98
# shellcheck disable=SC2034
STOP=11
start_service(){
 procd_open_instance
 procd_set_param command /usr/bin/kee-route-manager-ui serve --config /etc/kee-route-manager-ui/config.yaml
 procd_set_param respawn 3600 5 0
 procd_set_param stdout 1
 procd_set_param stderr 1
 procd_close_instance
}
